package com.mycompany.calculator_jr;

import javax.swing.JButton;

public class Calculator extends javax.swing.JFrame {

    private double operand1 = 0;
    private double operand2 = 0;
    private char operator;
    private boolean isTyping = false;
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        field = new javax.swing.JTextField();
        clearBTN = new javax.swing.JButton();
        eraseBTN = new javax.swing.JButton();
        moduloBTN = new javax.swing.JButton();
        divideBTN = new javax.swing.JButton();
        multiplyBTN = new javax.swing.JButton();
        subtractBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        equalBTN = new javax.swing.JButton();
        SEVEN = new javax.swing.JButton();
        EIGHT = new javax.swing.JButton();
        NINE = new javax.swing.JButton();
        SIX = new javax.swing.JButton();
        FIVE = new javax.swing.JButton();
        FOUR = new javax.swing.JButton();
        ONE = new javax.swing.JButton();
        TWO = new javax.swing.JButton();
        THREE = new javax.swing.JButton();
        ZERO = new javax.swing.JButton();
        decimalBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        field.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldActionPerformed(evt);
            }
        });

        clearBTN.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        clearBTN.setText("Clear");
        clearBTN.setPreferredSize(new java.awt.Dimension(50, 50));
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        eraseBTN.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        eraseBTN.setText("<--");
        eraseBTN.setPreferredSize(new java.awt.Dimension(50, 50));
        eraseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseBTNActionPerformed(evt);
            }
        });

        moduloBTN.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        moduloBTN.setText("%");
        moduloBTN.setPreferredSize(new java.awt.Dimension(50, 50));
        moduloBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloBTNActionPerformed(evt);
            }
        });

        divideBTN.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        divideBTN.setText("/");
        divideBTN.setPreferredSize(new java.awt.Dimension(50, 50));
        divideBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideBTNActionPerformed(evt);
            }
        });

        multiplyBTN.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        multiplyBTN.setText("X");
        multiplyBTN.setPreferredSize(new java.awt.Dimension(50, 50));
        multiplyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyBTNActionPerformed(evt);
            }
        });

        subtractBTN.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        subtractBTN.setText("-");
        subtractBTN.setPreferredSize(new java.awt.Dimension(50, 50));
        subtractBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractBTNActionPerformed(evt);
            }
        });

        addBTN.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        addBTN.setText("+");
        addBTN.setPreferredSize(new java.awt.Dimension(50, 50));
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        equalBTN.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        equalBTN.setText("=");
        equalBTN.setPreferredSize(new java.awt.Dimension(50, 50));
        equalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBTNActionPerformed(evt);
            }
        });

        SEVEN.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        SEVEN.setText("7");
        SEVEN.setPreferredSize(new java.awt.Dimension(50, 50));
        SEVEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEVENActionPerformed(evt);
            }
        });

        EIGHT.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        EIGHT.setText("8");
        EIGHT.setPreferredSize(new java.awt.Dimension(50, 50));
        EIGHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIGHTActionPerformed(evt);
            }
        });

        NINE.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        NINE.setText("9");
        NINE.setPreferredSize(new java.awt.Dimension(50, 50));
        NINE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NINEActionPerformed(evt);
            }
        });

        SIX.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        SIX.setText("6");
        SIX.setPreferredSize(new java.awt.Dimension(50, 50));
        SIX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIXActionPerformed(evt);
            }
        });

        FIVE.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        FIVE.setText("5");
        FIVE.setPreferredSize(new java.awt.Dimension(50, 50));
        FIVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIVEActionPerformed(evt);
            }
        });

        FOUR.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        FOUR.setText("4");
        FOUR.setPreferredSize(new java.awt.Dimension(50, 50));
        FOUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOURActionPerformed(evt);
            }
        });

        ONE.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        ONE.setText("1");
        ONE.setPreferredSize(new java.awt.Dimension(50, 50));
        ONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONEActionPerformed(evt);
            }
        });

        TWO.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        TWO.setText("2");
        TWO.setPreferredSize(new java.awt.Dimension(50, 50));
        TWO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TWOActionPerformed(evt);
            }
        });

        THREE.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        THREE.setText("3");
        THREE.setPreferredSize(new java.awt.Dimension(50, 50));
        THREE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THREEActionPerformed(evt);
            }
        });

        ZERO.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        ZERO.setText("0");
        ZERO.setPreferredSize(new java.awt.Dimension(50, 50));
        ZERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZEROActionPerformed(evt);
            }
        });

        decimalBTN.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        decimalBTN.setText(".");
        decimalBTN.setPreferredSize(new java.awt.Dimension(50, 50));
        decimalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel1.setText("Best Calculator in the Wooorld!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(field)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(SEVEN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ONE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FOUR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FIVE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TWO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ZERO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(EIGHT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(eraseBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(moduloBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(26, 26, 26)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(decimalBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(THREE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SIX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NINE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 2, Short.MAX_VALUE)
                                        .addComponent(equalBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(multiplyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(divideBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(subtractBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eraseBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moduloBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divideBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NINE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiplyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SIX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtractBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(THREE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decimalBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equalBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EIGHT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(FIVE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(TWO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(ZERO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SEVEN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(FOUR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(ONE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateDisplay(String value) {
        String currentText = field.getText();
        if (currentText.equals("0") || !isTyping) {
            field.setText(value);
            isTyping = true;
        } else {
            field.setText(currentText + value);
        }
    }
    
    private void digitButtonActionPerformed(JButton button) {
        String buttonText = button.getText();
        updateDisplay(buttonText);
    }
    
        //handle operator buttons
    private void operatorButtonActionPerformed(char op) {
        if (isTyping) {
            operand1 = Double.parseDouble(field.getText());
            operator = op;
            isTyping = false;
        }
    }
    
    private void fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        clearButtonActionPerformed();
    }//GEN-LAST:event_clearBTNActionPerformed

    //handle clear button
    private void clearButtonActionPerformed() {
        operand1 = 0;
        operand2 = 0;
        operator = ' ';
        field.setText("0");
        isTyping = false;
    }
    
    private void eraseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseBTNActionPerformed
        // TODO add your handling code here:
        if (isTyping && field.getText().length() > 0) {
            String currentText = field.getText();
            field.setText(currentText.substring(0, currentText.length() - 1));
            if (field.getText().isEmpty()) {
                field.setText("0");
                isTyping = false;
            }
        }
    }//GEN-LAST:event_eraseBTNActionPerformed

    private void moduloBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloBTNActionPerformed
        // TODO add your handling code here:
        operatorButtonActionPerformed('%');
    }//GEN-LAST:event_moduloBTNActionPerformed

    private void divideBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideBTNActionPerformed
        // TODO add your handling code here:
        operatorButtonActionPerformed('/');
    }//GEN-LAST:event_divideBTNActionPerformed

    private void multiplyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyBTNActionPerformed
        // TODO add your handling code here:
        operatorButtonActionPerformed('*');
    }//GEN-LAST:event_multiplyBTNActionPerformed

    private void subtractBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractBTNActionPerformed
        // TODO add your handling code here:
        operatorButtonActionPerformed('-');
    }//GEN-LAST:event_subtractBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        operatorButtonActionPerformed('+');
    }//GEN-LAST:event_addBTNActionPerformed

    private void equalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBTNActionPerformed
        // TODO add your handling code here:
        equalsButtonActionPerformed();
    }//GEN-LAST:event_equalBTNActionPerformed

    //handle equals button
    private void equalsButtonActionPerformed() {
        if (!isTyping) {
            return;
        }
        operand2 = Double.parseDouble(field.getText());
        double result = 0;
        switch (operator) {
            case '+':
                result = operand1 + operand2;
                break;
            case '-':
                result = operand1 - operand2;
                break;
            case '*':
                result = operand1 * operand2;
                break;
            case '/':
                if (operand2 != 0) {
                    result = operand1 / operand2;
                } else {
                    result = Double.POSITIVE_INFINITY; // Handle division by zero
                }
                break;
            case '%':
                result = operand1 % operand2;
                break;
        }
        field.setText(String.valueOf(result));
        isTyping = false;
    }
    
    private void SEVENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEVENActionPerformed
        // TODO add your handling code here:
        digitButtonActionPerformed(SEVEN);
    }//GEN-LAST:event_SEVENActionPerformed

    private void EIGHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIGHTActionPerformed
        // TODO add your handling code here:
        digitButtonActionPerformed(EIGHT);
    }//GEN-LAST:event_EIGHTActionPerformed

    private void NINEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NINEActionPerformed
        // TODO add your handling code here:
        digitButtonActionPerformed(NINE);
    }//GEN-LAST:event_NINEActionPerformed

    private void SIXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIXActionPerformed
        // TODO add your handling code here:
        digitButtonActionPerformed(SIX);
    }//GEN-LAST:event_SIXActionPerformed

    private void FIVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIVEActionPerformed
        // TODO add your handling code here:
        digitButtonActionPerformed(FIVE);
    }//GEN-LAST:event_FIVEActionPerformed

    private void FOURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOURActionPerformed
        // TODO add your handling code here:
        digitButtonActionPerformed(FOUR);
    }//GEN-LAST:event_FOURActionPerformed

    private void ONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONEActionPerformed
        // TODO add your handling code here:
        digitButtonActionPerformed(ONE);
    }//GEN-LAST:event_ONEActionPerformed

    private void TWOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TWOActionPerformed
        // TODO add your handling code here:
        digitButtonActionPerformed(TWO);
    }//GEN-LAST:event_TWOActionPerformed

    private void THREEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THREEActionPerformed
        // TODO add your handling code here:
        digitButtonActionPerformed(THREE);
    }//GEN-LAST:event_THREEActionPerformed

    private void ZEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZEROActionPerformed
        // TODO add your handling code here:
        digitButtonActionPerformed(ZERO);
    }//GEN-LAST:event_ZEROActionPerformed

    private void decimalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalBTNActionPerformed
        // TODO add your handling code here:
        String currentText = field.getText();
        if (!currentText.contains(".")) {
            updateDisplay(".");
        }
    }//GEN-LAST:event_decimalBTNActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EIGHT;
    private javax.swing.JButton FIVE;
    private javax.swing.JButton FOUR;
    private javax.swing.JButton NINE;
    private javax.swing.JButton ONE;
    private javax.swing.JButton SEVEN;
    private javax.swing.JButton SIX;
    private javax.swing.JButton THREE;
    private javax.swing.JButton TWO;
    private javax.swing.JButton ZERO;
    private javax.swing.JButton addBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton decimalBTN;
    private javax.swing.JButton divideBTN;
    private javax.swing.JButton equalBTN;
    private javax.swing.JButton eraseBTN;
    private javax.swing.JTextField field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton moduloBTN;
    private javax.swing.JButton multiplyBTN;
    private javax.swing.JButton subtractBTN;
    // End of variables declaration//GEN-END:variables
}
